183928989: Create Saas Frequency Client JS
LibertyDSNP/saas-frequency-client-js pull request #1
Opened 2023-02-16 16:40 UTC by tedward111

2023-02-16 17:29 UTC, abadaa commented on src/defaultFrequencyClient.ts
> +        ipfsMessageCid: string,
doesn't matter much but can we flip the order of the cid and schema id parameters to match the addIpfsMessage params?

2023-02-16 17:48 UTC, abadaa commented on README.md
> +3. Start up the frequency instant-seal-node: `docker run -d -p 9944:9944 frequencychain/instant-seal-node:v0.9.29`
We should update this frequency to the latest version

2023-02-16 17:51 UTC, pfrank13 requested changes
Haven't reviewed anything, npm test is failing for me when trying to test, this isn't using TestContainers I'd imagine? That needs to be fixed.

2023-02-16 18:17 UTC, abadaa requested changes
Just a couple changes with which docker image/frequency version we're using, and an amendment to the AddMessage test to handle a case where the MSA id doesn't exist

2023-02-16 18:17 UTC, abadaa commented on src/polkadotApi.test.ts
> +    test("should successfully add ipfs message", async () => {
This will technically fail if you only run this test on a fresh start up on the docker image because an MSA Id won't exist in the container. The test will pass anyway. but if you check the gui and do the rpc call to get messages, it'll return empty. However, if you add the step to create the Msa prior, it'll work as intended.

It's not something that CI would catch but wanted to bring it up. I suggest we do a check in the test first for an MSA, and if there isn't one to create one first.

2023-02-16 18:38 UTC, tedward111 commented on src/polkadotApi.test.ts
> +describe("Test Polkadot Frequency functionality for Msa, Schema, and Messages", () => {
@pfrank13 Let me know if this should be in scope for this ticket.

2023-02-16 18:47 UTC, pfrank13 commented on src/polkadotApi.test.ts
> +describe("Test Polkadot Frequency functionality for Msa, Schema, and Messages", () => {
Yup, it's the testing approach we use oin every single project that we have; also, this approach doesn't work for CI

2023-02-16 18:48 UTC, pfrank13 commented on src/polkadotApi.test.ts
> +describe("Test Polkadot Frequency functionality for Msa, Schema, and Messages", () => {
Also, look at the content-indexer, graph indexer for how to do this in TS, but it's almost identical to how it works in the announcer, custodial-wallet and saas-frequency-client for the jVM @tedward111

2023-02-16 19:13 UTC, pfrank13 commented on src/polkadotApi.test.ts
> +describe("Test Polkadot Frequency functionality for Msa, Schema, and Messages", () => {
@tedward111 sorry didn't look at what I was responding to, no this is not in scope, the assumption for this ticket there was going to be an image with schemas that would allow the creation of a batch message.

2023-02-16 22:10 UTC, Ajaxan commented on README.md
> +3. Start up the frequency instant-seal-node: `docker run -d -p 9944:9944 frequencychain/instant-seal-node:v0.9.29`
Should this use the instant seal node with the schemas built in that you worked on @abadaa?

2023-02-16 22:30 UTC, pfrank13 requested changes

2023-02-16 22:30 UTC, pfrank13 commented on README.md
> +3. Start up the frequency instant-seal-node: `docker run -d -p 9944:9944 frequencychain/instant-seal-node:v0.9.29`
Yeah current version is 1.2.0

2023-02-16 22:30 UTC, pfrank13 commented on package.json
> +    "@polkadot/typegen": "^9.6.2",
You will want to look at the integration tests for Frequency to get this configuration right because we are no longer matching the polkadot version numbers.

2023-02-16 22:30 UTC, pfrank13 commented on src/defaultFrequencyClient.ts
> +    }
Can you change this function to be called `.newInstance()` as it's a factory method. Nice workaround for async await didn't catch what was going on there at first.

2023-02-16 22:30 UTC, pfrank13 commented on src/defaultFrequencyClient.ts
> +                    console.log("Transaction status:", status.type);
No console.logs, if there is value here please use a logger, see the COntentIndexer for Loggers that we use.

2023-02-16 22:30 UTC, pfrank13 commented on src/defaultFrequencyClient.ts
> +                        console.log("Events:");
No console.logs, if there is value here please use a logger, see the COntentIndexer for Loggers that we use.

2023-02-16 22:30 UTC, pfrank13 commented on src/defaultFrequencyClient.ts
> +                            console.log(
No console.logs, if there is value here please use a logger, see the COntentIndexer for Loggers that we use.

2023-02-16 22:30 UTC, pfrank13 commented on src/defaultFrequencyClient.ts
> +                                        console.log(`${section}.${method}: ${docs.join(" ")}`);
No console.logs, if there is value here please use a logger, see the COntentIndexer for Loggers that we use.

2023-02-16 22:30 UTC, pfrank13 commented on src/defaultFrequencyClient.ts
> +                                    }
No console.logs, if there is value here please use a logger, see the COntentIndexer for Loggers that we use.

2023-02-16 22:30 UTC, pfrank13 commented on src/frequencyClient.ts
> +    keyringPair: KeyringPair,
These are exposing implementation details, the interface should just expose what can be done not the "HOW" it is done.

2023-02-16 22:30 UTC, pfrank13 commented on src/frequencyClient.ts
> +    getMsa: () => Promise<GetMsaResult>;
instead of making these arrow functions just make them standard functions, e.g. https://github.com/Liberty30/content-indexer/blob/main/src/service/indexing.ts#L1097

2023-02-16 22:30 UTC, pfrank13 commented on src/frequencyClient.ts
> +}
Remove the underscores, I'm assuming you kept them because the internal library has underscores (prolly cause Rust does) but we don't want to pull that forward, camelCase so you'll need to do a bit of mapping.

2023-02-16 22:30 UTC, pfrank13 commented on src/defaultFrequencyClient.ts
> +export class DefaultFrequencyClient implements FrequencyClient{
kill the arrow function in favor of just standard class level functions

2023-02-16 22:30 UTC, pfrank13 commented on src/frequencyClient.ts
> +    unsubscribe: () => void;
We don't want to expose this

2023-02-16 22:30 UTC, pfrank13 commented on src/frequencyClient.ts
> +    unsubscribe: () => void;
We don't want to expose this

2023-02-16 22:30 UTC, pfrank13 commented on src/defaultFrequencyClient.ts
> +export class DefaultFrequencyClient implements FrequencyClient{
Please remove unsubscribe from any of the return types, that should be called via a `finally{}` block or a `.finally(() => {})` via Promises (although I think you are using async await for everything must of the time. Basically that's an internal implementation detail that the caller need not care about.

2023-02-16 23:08 UTC, Ajaxan requested changes
A lot of the things that need to change are from where I was lazy in my POC and the fact we need to be more on top of things in an actual application of the polkadot api

2023-02-16 23:08 UTC, Ajaxan commented on src/polkadotApi.test.ts
> +        console.log(retrieveMessageResult.result)
I know this is what I did on the poc, but for real tests in the actual client I don't think this is reliable. You'll have to figure out a way to assert on some real data that is returned so we know it's working. Preferably by decoding that cid.

2023-02-16 23:08 UTC, Ajaxan commented on src/polkadotApi.test.ts
> +import "@frequency-chain/api-augment";
I'd rename this file to defaultFrequencyClient.test.ts

2023-02-16 23:08 UTC, Ajaxan commented on src/polkadotApi.test.ts
> +        frequencyClient = await DefaultFrequencyClient.initialize(process.env.WS_PROVIDER_URL!!, "//Alice")
Do we need the `WS_PROVIDER_URL` to be in an ENV file here?

2023-02-27 00:01 UTC, abadaa approved these changes
Just a readme suggestion but otherwise it looks like things are working as expected given the scope of this

2023-02-27 20:06 UTC, Ajaxan requested changes
Just a few things left I noticed, but it's looking real close

2023-02-27 20:06 UTC, Ajaxan commented on src/defaultFrequencyClient.ts
> +          console.log("Transaction status:", status.type);
Should probably remove this log statement

2023-02-27 20:06 UTC, Ajaxan commented on src/defaultFrequencyClient.ts
> +      cid: messageResponse.cid.value,
This whole mapping thing looked like a headache, nicely done. One final thing I'd suggest is taking this from a bytearray to a string for the cid. My thinking is that since we are passing in the cid as a string for the add message call it makes sense to return a string for the cid in the get messages call.

2023-02-27 20:06 UTC, Ajaxan commented on src/defaultFrequencyClient.ts
> +    });
I'm concerned about using a timer for the unsubscribe. Imagine a world where we are having thousands of requests going through a second. I'm worried these could end up piling up and causing problems. I'm not entirely sure how it'll end up going though... @pfrank13 Is that a valid concern or is it a nonissue?

2023-03-01 19:56 UTC, pfrank13 requested changes
Move unsubscribe into a finally block

2023-03-01 19:56 UTC, pfrank13 commented on src/defaultFrequencyClient.ts
> +    });
Yeah this should be in a finally block

2023-03-03 01:47 UTC, closed without merging